name: Build release
on:
  workflow_dispatch:  
jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - name: Download Assets
        uses: i3h/download-release-asset@v1.3.3
        with:
          owner: cheat
          repo: cheat 
          tag: ${{ steps.get_release.outputs.RELEASE_TAG  }}
          file: cheat-linux-amd64.gz
          path:  ${{ env.buildroot }}/tmp

      - name: Decompress package
        run: gunzip ${{ env.buildroot }}/tmp/cheat-linux-amd64.gz
            
      - name: create sample script
        run: |
          mkdir -p .debpkg/usr/local/bin
          cp ${{ env.buildroot }}/tmp/cheat-linux-amd64 .debpkg/usr/local/bin/cheat
          chmod +x .debpkg/usr/local/bin/cheat
          
      - uses: jiro4989/build-deb-action@v3
        with:
          package: cheat
          package_root: .debpkg
          maintainer: cdorsman
          version: ${{ steps.get_release.outputs.RELEASE_TAG  }}
          arch: 'amd64'
          desc: 'With cheat you can create and view interactive cheatsheets on the command-line.'
          homepage: 'https://github.com/jiro4989/build-deb-action'
