name: Check
on:
  schedule:
    - cron: '0 0 1 1-12 *'
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - name: Get latest release from cheat
        id: get_release
        shell: bash
        run: |
          # Fetch release information and extract the release tag
          echo "URL=https://api.github.com/repos/${{ vars.REPO_NAME }}/${{ vars.APP_NAME }}/releases/latest" >> $GITHUB_ENV
          RELEASE_TAG_SRC="$(curl -sL $(echo $URL) | jq -r '.tag_name')"
          echo "release_tag=$RELEASE_TAG_SRC" >> $GITHUB_OUTPUT
          echo "release_tag=$RELEASE_TAG_SRC" >> $GITHUB_ENV
          echo "latest release: $RELEASE_TAG_SRC"

     # - name: Get latest tag from repo
        


      # Need check for version
          
      #- name: Call workflow to build code
      #  uses: benc-uk/workflow-dispatch@v1
      #  with:
      #    workflow: build.yml
