name: Check
on:
  schedule:
    - cron: '0 0 1 1-12 *'
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - name: Get latest release from cheat
        id: get_release_src
        shell: bash
        run: |
          # Fetch release information and extract the release tag
          URL="https://api.github.com/repos/${{ vars.REPO_NAME }}/${{ vars.APP_NAME }}/releases/latest"
          RELEASE_TAG_SRC="$(curl -sL $URL | jq -r '.tag_name')"
          echo "release_tag=$RELEASE_TAG_SRC" >> $GITHUB_OUTPUT
          echo "release_tag=$RELEASE_TAG_SRC" >> $GITHUB_ENV
          echo "latest release: $RELEASE_TAG_SRC" 

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: 'Get Previous tag'
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Compare source with dest repo
        id: compare_versions
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        shell: bash
        run: |
            if [[ "${{ steps.previoustag.outputs.tag }}" == "${{ steps.get_release_src.outputs.RELEASE_TAG_SRC }}" ]]; then
                gh run cancel ${{ github.run_id }}
            fi
        
      - name: Start build    
        uses: benc-uk/workflow-dispatch@v1 
        with:
          workflow: build.yml
    
